### PR TITLE
Replaced 1.9.3 autocalc setting with a delay

### PR DESCRIPTION
**Pull request by captain828**
Also cleaned up the settings, though may need some playing around with the UI sorting.

Version already bumped to 1.9.4 - change as needed.

Delay logic:
* coroutine call from ShipUpdatedEvent which delays execution for _recalcDelaySec_
* if an extra ShipUpdatedEvent is fired, then the current coroutine is stopped and a new one is started
* basically debounce

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Hi,
I'm getting a lot of reports about this not working in the thread.  Care to take a look before I do any reverts?

**Comment by captain828** [comment]
Yeah, I'll take a look.

**Comment by captain828** [comment]
There were a number of changes that should be checked separately:
1. the framework version changed from 4.5 to 4.7.2: _shouldn't_ be the problem but it could cause unknown issues if KSP doesn't play nice with 4.7.2
2. KSPAddon.once changing to true requires more careful cleanup between scene changes: I suspect this is the likely culprit but I'm not familiar with all the internal workings of SR
3. the coroutine that delays the ship recalculation: outside of the nre that I didn't catch when scene changes from editor to KSC, this shouldn't affect other parts of the mod

I would recommend reverting to 1.9.2 or 1.9.3 and checking the effect of 2), then 1). 
3) needs to be better tested with 2) as it could cause issues. 2) wasn't implemented when I tested it.

**Comment by linuxgurugamer** [comment]
Framework version doesn't matter, as long as it is 4, it's fine.  And, when I do my release builds, they all get built the same way, on my Jenkins server, which doesn't pay attention to the framework version in the csproj.

Thanks for looking, I'll do some more work on it later.

**Pull request merged**
